---

ansible_user: deployer
become: true
main_uid: "1100"
main_gid: "1100"
pushover_user_key: "{{ vault_pushover_user_key }}"
pushover_api_bootlace: "{{ vault_pushover_token }}"
pushover_token: "{{ vault_pushover_token }}"

# https://github.com/ironicbadger/infra/blob/master/group_vars/all.yaml
# ironicbadger.bash_aliases
bash_aliases:
  - { alias: "dcp", command: "docker-compose "}
  - { alias: "dlog", command: "docker logs -f "}
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop "}
  - { alias: "hdtemp", command: "sudo hddtemp /dev/sd[a,b,c,d,e,f,g,h,i,j,k,l,m,n]"}

# grog.package
package_list:
- name: curl
- name: git
- name: hddtemp
- name: parted
- name: htop
- name: iftop
- name: iotop
- name: lm-sensors
- name: net-tools
- name: openssh-server
- name: python3
- name: tmux
- name: sudo
- name: wget
- name: tree
- name: smartmontools
- name: qemu-guest-agent
- name: open-vm-tools
- name: nmap

# geerlingguy.ntp
ntp_timezone: "America/Chicago"

# geerlingguy.docker
docker_compose_version: 1.29.2

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /home/deployer/services

# influxdb
influxdb_ip: "{{ vault_influx_ip }}"
influxdb_port: 8086

## telegraf
telegraf_influxdb_urls:
  - "http://{{ influxdb_ip }}:{{ influxdb_port }}"
telegraf_influxdb_database: telegraf
telegraf_influxdb_username: root
telegraf_influxdb_password: "{{ vault_telegraf_influxdb_password }}"
telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      collect_cpu_time: "false"
      report_active: "false"
  - name: disk
    options:
      ignore_fs:
        - "tmpfs"
        - "devtmpfs"
        - "devfs"
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: kernel
  - name: processes
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      perdevice: "true"
  - name: hddtemp
  - name: net
    options:
      interfaces:
        - "ens192"
  - name: sensors