---
domain_name: "{{ vault_domain_name }}"
nas_ip: "{{ vault_nas_ip }}"
nfs_iso_export: "{{ vault_nfs_iso_export }}"
nfs_pvedata_export: "{{ vault_nfs_pvedata_export }}"
init_admin_pass: "{{ vault_init_admin_password }}"
photoprism_db_password: "{{ vault_photoprism_db_password }}"
nextcloud_db_password: "{{ vault_nextcloud_db_password }}"
nextcloud_root_db_password: "{{ vault_nextcloud_root_db_password }}"
cloudflare_account_email: "{{ vault_cf_email }}"
cloudflare_api_key: "{{ vault_cf_api_key }}"
wordpress_shop_db_password: "{{ vault_wordpress_shop_db_password }}"
wordpress_shop_root_db_password: "{{ vault_wordpress_shop_root_db_password }}"
peertube_db_password: "{{ vault_peertube_db_password }}"
peertube_secret: "{{ vault_peertube_secret }}"
admin_email: "{{ vault_admin_email }}"
peertube_admin_password: "{{ vault_peertube_admin_password }}"
joplin_postgres_password: "{{ vault_joplin_postgres_password }}"

# apprise
apprise_path: /usr/local/bin/apprise

# grog.package
package_list:
- name: curl
- name: git
- name: htop
- name: iftop
- name: iotop
- name: net-tools
- name: openssh-server
- name: python3
- name: tmux
- name: sudo
- name: wget
- name: tree
- name: nmap
- name: intel-gpu-tools
- name: ffmpeg
- name: vainfo
- name: lshw
- name: pciutils
- name: intel-media-va-driver

# ironicbadger.docker_compose_generator
appdata_path: "/appdata"
traefik_config_filepath: "{{ appdata_path }}/traefik"

local_domain: "{{ vault_domain_name }}"

# lm-traefik
traefik_file_provider: true
traefik_enable_dashboard: true #defaults to false
traefik_insecure_transport: false #defaults to false
traefik_exposed_by_default: false
