---
interface_name: eno1
interfaces_template: "proxmox/interfaces.j2"
proxmox_pass: "{{ vault_proxmox_pass }}"
host_ip: "{{ ansible_host }}/24"
gateway_ip: "{{ vault_gateway_ip }}"
domain_name: "{{ vault_domain_name }}"
nfs_iso_export: "{{ vault_nfs_iso_export }}"
nfs_pvedata_export: "{{ vault_nfs_pvedata_export }}"
init_admin_pass: "{{ vault_init_admin_password }}"
photoprism_db_password: "{{ vault_photoprism_db_password }}"
cloudflare_account_email: "{{ vault_cf_email }}"
cloudflare_api_key: "{{ vault_cf_api_key }}"
wordpress_shop_db_password: "{{ vault_wordpress_shop_db_password }}"
wordpress_shop_root_db_password: "{{ vault_wordpress_shop_root_db_password }}"
peertube_db_password: "{{ vault_peertube_db_password }}"
peertube_secret: "{{ vault_peertube_secret }}"
admin_email: "{{ vault_admin_email }}"
peertube_admin_password: "{{ vault_peertube_admin_password }}"
joplin_postgres_password: "{{ vault_joplin_postgres_password }}"

# apprise
apprise_path: /usr/local/bin/apprise

# influxdb
influxdb_ip: 127.0.0.1

# grog.package
package_list:
- name: curl
- name: git
- name: parted
- name: htop
- name: iftop
- name: iotop
- name: powertop
- name: lm-sensors
- name: net-tools
- name: openssh-server
- name: python3
- name: tmux
- name: sudo
- name: wget
- name: tree
- name: smartmontools
- name: nmap
- name: intel-gpu-tools
- name: nfs-kernel-server
- name: zfsutils-linux
- name: ffmpeg
- name: vainfo
- name: lshw
- name: pciutils
- name: intel-media-va-driver

## telegraf
telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      collect_cpu_time: "false"
      report_active: "false"
  - name: disk
    options:
      ignore_fs:
        - "tmpfs"
        - "devtmpfs"
        - "devfs"
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: kernel
  - name: processes
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      perdevice: "true"
  - name: hddtemp
  - name: net
    options:
      interfaces:
        - "ens192"
        - "eno1"
  - name: sensors

# lm-traefik
traefik_file_provider: true
traefik_enable_dashboard: true #defaults to false
traefik_insecure_transport: false #defaults to false
traefik_exposed_by_default: false
