---

ansible_host: "{{ vault_influxdb_ip }}"

#########################################################
### Proxmox API connection and authentication section ###
#########################################################
pve_default_behavior: no_defaults
pve_node: pve3
pve_api_host: "{{ vault_pve3_host_ip }}"
pve_api_user: root@pam
pve_api_password: "{{ vault_proxmox_api_password }}"
# pve_api_token_id: root@pam!ansible
# pve_api_token_secret: "{{ vault_pve2_root_api_password }}"

#####################################
### Container OS template section ###
#####################################
pve_lxc_ostemplate_name: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
pve_lxc_ostemplate_storage: local
pve_lxc_ostemplate_content_type: vztmpl
pve_lxc_ostemplate_timeout: 60
pve_lxc_ostemplate_force: no
pve_lxc_ostemplate_state: present

##############################################
### Container resources definition section ###
##############################################
pve_lxc_timeout: 30
pve_hostname: "{{ inventory_hostname.split('.')[0] }}"
pve_lxc_vmid: 301
pve_lxc_description: |
  This host is an Ubuntu 22-04 container configured via Ansible with:
  - 2 CPU cores
  - 1024MB of RAM
  - 50GB of system disk
  - unprivileged: yes
  - onboot: no
  Designed to run influxdb for the smart home
pve_lxc_root_password: "{{ vault_influxdb_lxc_root_password }}"
pve_lxc_root_authorized_pubkey: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"

pve_lxc_cpu_cores: 2
pve_lxc_memory: 1024
pve_lxc_swap: 512
pve_lxc_disk: 50
pve_lxc_storage: local-lvm
pve_onboot: no
pve_lxc_searchdomain: "{{ vault_searchdomain }}"
pve_lxc_unprivileged: yes
pve_lxc_force: no
pve_lxc_features:
  - nesting=1
pve_lxc_net_interfaces:
  - id: net0
    name: eth0
    bridge: vmbr0
    hwaddr: 3A:A4:62:5E:97:39
    ip4: "{{ vault_influxdb_lxc_ip }}"
    netmask4: "24"
    gw4: "{{ vault_gateway_ip }}"

# List of additional mount points and their characteristics
# pve_lxc_mounts:
#   - id: mp0
#     storage: local-lvm
#     size: 16
#     mount_point: "/mnt/data"
#     acl: false                     # Optional.
#     quota: false                   # Optional.
#     backup: false                  # Optional.
#     skip_replication: false        # Optional.
#     read_only: false               # Optional.
#   - id: mp1
#     storage: local-lvm
#     size: 8
#     mount_point: "/mnt/logs"

# Additional "manual" settings to add to the file /etc/pve/nodes/{{ node }}/lxc/{{ VMID }}.conf
# pve_lxc_additional_configurations: []
#     # Kernel modules available within the LXC
#   - regexp: '^mp0'
#     line: 'mp0: /lib/modules/4.15.18-9-pve,mp=/lib/modules/4.15.18-9-pve,ro=1'
#     state: present
#     # Enable/Disable additional features
#   - regexp: '^features'
#     line: 'features: nesting=1'
#     state: present
#     # tun device for OpenVPN server inside LXC
#   - regexp: '^lxc.cgroup.devices.allow'
#     line: 'lxc.cgroup.devices.allow = c 10:200 rwm'
#     state: present
#   - regexp: '^lxc.hook.autodev'
#     line: 'lxc.hook.autodev = sh -c "modprobe tun; cd ${LXC_ROOTFS_MOUNT}/dev; mkdir net; mknod net/tun c 10 200; chmod 0666 net/tun"'
#     state: present

appdata_path: "/appdata"

containers: 
  - service_name: influxdb
    active: true
    image: influxdb:2.7
    environment:
      - MODE=standalone
      - TELEMETRY=false
      - DOCKER_INFLUXDB_INIT_MODE=upgrade
      - DOCKER_INFLUXDB_INIT_USERNAME=homeassistant
      - DOCKER_INFLUXDB_INIT_PASSWORD={{ vault_influxdb_homeassistant_password }}
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=homeassistant
    include_global_env_vars: true
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/influxdb/data:/var/lib/influxdb"
      - "{{ appdata_path }}/influxdb/config:/etc/influxdb"
      - "{{ appdata_path }}/influxdb/homeassistant:/backups"
      - "{{ appdata_path }}/influxdb2/data:/var/lib/influxdb2"
      - "{{ appdata_path }}/influxdb2/config:/etc/influxdb2"
    ports:
      - 8086:8086