services:
  jellyfin:
    image: jellyfin/jellyfin:2024123005
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.{{ local_domain }}`)"
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    volumes:
      - "{{ appdata_path }}/jellyfin:/config"
      - "{{ media_path }}books:/data/books"
      - "{{ media_path }}movies:/data/movies"
      - "{{ media_path }}tvshows:/data/tvshows"
      - "{{ media_path }}videos:/data/videos"
    environment:
      - "JELLYFIN_PublishedServerUrl=jellyfin.{{ local_domain }}"
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"
    restart: unless-stopped