services:
  jellyfin:
    image: jellyfin/jellyfin:2025092205
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.{{ local_domain }}`)"
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    volumes:
      - "{{ appdata_path }}/jellyfin:/config"
      - "{{ media_dataset_path }}:/media"
      - "{{ media_path }}books:/data/books"
      - "{{ media_path }}movies:/data/movies"
      - "{{ media_path }}tvshows:/data/tvshows"
      - "{{ media_path }}videos:/data/videos"
    environment:
      - "JELLYFIN_PublishedServerUrl=jellyfin.{{ local_domain }}"
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - "TZ={{ ntp_timezone }}"
      - PORT=5055
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
    volumes:
      - "{{ appdata_path }}jellyseer/config:/app/config"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.{{ local_domain }}`)"
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    container_name: configarr
    #user: 1000:1000 # Optional, defaults to root:root
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"
    volumes:
      - "{{ appdata_path }}/configarr/config:/app/config" # Contains the config.yml and secrets.yml
      - "{{ appdata_path }}/configarr/dockerrepos:/app/repos" # Cache repositories
      # - ./custom/cfs:/app/cfs # Optional if custom formats locally provided
      # - ./custom/templates:/app/templates # Optional if custom templates
    restart: "no" # optional make sure this is set to no or removed. Default is no