---
- hosts: docker-lxc
  become: true
  vars_files: vault.yaml
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - deployer
    - role: docker_config
      tags: docker_config
    - role: ironicbadger.bash_aliases
    - role: grog.package
    # - role: lm-coraltpu
    # - role: mount_backup_disk
    - role: ironicbadger.docker_compose_generator
      tags: compose
    # - role: lm-traefik
    #   tags: compose
    # - role: lm-frigate-config
    #   tags: compose
    - role: docker_compose_up
      tags: compose
    # - role: lm-photoprism
    #   tags: compose
    # - role: rossmcdonald.telegraf
    # - role: zed_pushover
    # - role: ironicbadger.hddtemp
    # - role: ironicbadger.proxmox_nag_removal
    # - role: ironicbadger.apprise_boot_notification
    # - role: disk_alerts
    
    
