- src: geerlingguy.docker
- src: ironicbadger.proxmox_nag_removal
- src: geerlingguy.ntp
- src: lae.proxmox
- src: mrlesmithjr.zfs
- src: nununo.proxmox_haos_install
- src: grog.package
- src: rossmcdonald.telegraf
- src: ironicbadger.bash_aliases
- src: ironicbadger.hddtemp
- src: ironicbadger.docker_compose_generator
- src: ironicbadger.apprise_boot_notification