- src: geerlingguy.docker
- src: ironicbadger.proxmox_nag_removal
- src: geerlingguy.ntp
- src: lae.proxmox
- src: mrlesmithjr.zfs
- src: nununo.proxmox_haos_install
- src: grog.package
- src: rossmcdonald.telegraf
- src: ironicbadger.bash_aliases
- src: ironicbadger.hddtemp
- src: ironicbadger.docker_compose_generator
- name: ironicbadger.apprise_boot_notification
  src: https://github.com/lmilius-homelab/ansible-role-apprise-boot-notification.git
- name: udelarinterior.proxmox_create_lxc
  src: https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc.git