---
# Install ssh key
# - hosts: local
#   gather_facts: yes
#   tasks:
#     - name: Ensure .ssh directory exists
#       file:
#         dest: "~/.ssh"
#         mode: 0700
#         owner: "{{ ansible_user_id }}"
#         state: directory
    
#     - name: Install ssh key
#       copy:
#         src: ./ssh_key
#         dest: "~/.ssh/ansible_key"
#         mode: 0600
#         owner: "{{ ansible_user_id }}"

# Bootstrap hosts
# - hosts: all
#   become: true
#   gather_facts: no
#   vars_files:
#     - vars/vault.yaml
#   roles:
#     - envsetup

- hosts: pve1
  become: true
  vars_files:
    - vars/vault.yaml
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - deployer
    - role: docker_config
      tags: docker_config
    - role: ironicbadger.bash_aliases
    - role: grog.package
    - role: lm-hddtemp
    - role: lm-coraltpu
    - role: mount_backup_disk
    - role: ironicbadger.docker_compose_generator
      tags: compose
    - role: lm-traefik
      tags: compose
    - role: lm-frigate-config
      tags: compose
    - role: docker_compose_up
      tags: compose
    # - role: rossmcdonald.telegraf
    #   tags: telegraf
    - role: zed_pushover
    - role: ironicbadger.proxmox_nag_removal
    # - role: ironicbadger.apprise_boot_notification
    - role: disk_alerts

- hosts: pve2
  become: true
  vars_files:
    - vars/vault.yaml
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - deployer
    - role: docker_config
      tags: docker_config
    - role: ironicbadger.bash_aliases
    - role: grog.package
    - role: lm-hddtemp
    # - role: lm-coraltpu
    # - role: ironicbadger.docker_compose_generator
    #   tags: compose
    # - role: lm-traefik
    #   tags: compose
    # - role: lm-frigate-config
    #   tags: compose
    # - role: docker_compose_up
    #   tags: compose
    # - role: rossmcdonald.telegraf
    - role: zed_pushover
    - role: ironicbadger.proxmox_nag_removal
    # - role: ironicbadger.apprise_boot_notification
    - role: disk_alerts

- hosts: pve3
  become: true
  vars_files:
    - vars/vault.yaml
  roles:
    - role: ironicbadger.proxmox_nag_removal
    - role: lm-hddtemp
    - role: ironicbadger.bash_aliases
    - role: grog.package
    - role: zed_pushover
    # - role: ironicbadger.apprise_boot_notification
    - role: disk_alerts
    # - role: rossmcdonald.telegraf
  
- hosts: dockerlxc
  become: true
  vars_files:
    - vars/vault.yaml
  gather_facts: no
  roles:
    - role: udelarinterior.proxmox_create_lxc

- hosts: dockerlxc
  become: true
  vars_files:
    - vars/vault.yaml
  gather_facts: yes
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - deployer
    - role: docker_config
      tags: docker_config
    - role: ironicbadger.bash_aliases
    - role: grog.package

- hosts: 
  - docker-prod-01
  # - frigate
  - kms
  - media
  become: true
  vars_files:
    - vars/vault.yaml
  gather_facts: yes
  roles:
    - role: lm-traefik
      tags: compose

# - hosts: frigate
#   become: true
#   vars_files: vars/vault.yaml
#   gather_facts: yes
#   roles:
#     - role: lm-coraltpu
#     - role: lm-frigate-config
#       tags: compose


- hosts: dockerlxc
  become: true
  vars_files:
    - vars/vault.yaml
  gather_facts: yes
  roles:
    - role: ironicbadger.docker_compose_generator
      tags: compose
    - role: docker_compose_up
      tags: compose