---
# Install ssh key
# - hosts: local
#   gather_facts: yes
#   tasks:
#     - name: Ensure .ssh directory exists
#       file:
#         dest: "~/.ssh"
#         mode: 0700
#         owner: "{{ ansible_user_id }}"
#         state: directory
    
#     - name: Install ssh key
#       copy:
#         src: ./ssh_key
#         dest: "~/.ssh/ansible_key"
#         mode: 0600
#         owner: "{{ ansible_user_id }}"

# Bootstrap hosts
# - hosts: all
#   become: true
#   gather_facts: no
#   vars_files:
#     - vars/vault.yaml
#   roles:
#     - envsetup

- hosts: 
    - nixos
  become: true
  vars_files:
    - vars/vault.yaml
  gather_facts: yes
  roles:
    - role: lm-traefik
      tags: compose
    - role: ironicbadger.docker_compose_generator
      tags: compose
    - role: docker_compose_up
      tags: compose