---
- name: ensure target dir exists
  ansible.builtin.file:
    dest: "{{ traefik_config_filepath }}/"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"

- name: template traefik config
  ansible.builtin.template:
    src: templates/traefik.yaml.j2
    dest: "{{ traefik_config_filepath }}/traefik.yaml"
    force: yes
    # unsafe_writes: yes
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  tags: traefik

- name: copy traefik rules
  ansible.builtin.template:
    src: templates/rules.yaml.j2
    dest: "{{ traefik_config_filepath }}/rules.yaml"
    force: yes
    # unsafe_writes: yes
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  when: traefik_file_provider
  tags: traefik