---

containers: 
  - service_name: librespeed
    active: true
    image: linuxserver/librespeed
    labels:
      - traefik.enable=true
      - "traefik.http.routers.librespeed.rule=Host(`speed.{{ local_domain }}`)"
    environment:
      - MODE=standalone
      - TELEMETRY=false
      # - "PASSWORD={{ librespeed_password }}"
    include_global_env_vars: true
    restart: unless-stopped
    ports:
      - 8080:80