services:
  immich:
    restart: unless-stopped
    image: "ghcr.io/immich-app/immich-server:{{ immich_release_version }}"
    container_name: immich
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "{{ immich_dir }}/library:/usr/src/app/upload"
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - "traefik.http.routers.immich.rule=Host(`immich.{{ local_domain }}`)"
      - traefik.http.services.immich.loadbalancer.server.port=2283
    expose:
      - 2283
    depends_on:
      - immich_redis
      - immich_database
    environment:
      - "DB_DATABASE_NAME=immich"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD={{ immich_db_password }}"
      - REDIS_HOSTNAME=immich_redis
      - DB_HOSTNAME=immich_database
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"
  
  ###
  immich_ml:
    restart: unless-stopped
    hostname: immich-machine-learning
    image: "ghcr.io/immich-app/immich-machine-learning:{{ immich_release_version }}"
    container_name: immich_ml
    # device_cgroup_rules:
    #   - 'c 189:* rmw'
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - "{{ immich_dir }}/model-cache:/cache"
      # - /dev/bus/usb:/dev/bus/usb
    
  ###
  immich_redis:
    restart: unless-stopped
    image: "docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571"
    container_name: immich_redis
    healthcheck:
      test: redis-cli ping || exit 1
    
  ###
  immich_database:
    restart: unless-stopped
    image: "ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84"
    container_name: immich_database
    environment:
      - "POSTGRES_PASSWORD={{ immich_db_password }}"
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
      - "POSTGRES_INITDB_ARGS='--data-checksums'"
      - "DB_STORAGE_TYPE=HDD"
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"
    volumes:
      - "{{ immich_dir }}/database:/var/lib/postgresql/data"