services:
  # Terminal | docker-compose exec photoprism bash
  # Help     | docker-compose exec photoprism photoprism help
  # Config   | docker-compose exec photoprism photoprism config
  # Reset    | docker-compose exec photoprism photoprism reset
  # Backup   | docker-compose exec photoprism photoprism backup -a -i
  # Restore  | docker-compose exec photoprism photoprism restore -a -i
  # Index    | docker-compose exec photoprism photoprism index
  # Reindex  | docker-compose exec photoprism photoprism index -f
  # Import   | docker-compose exec photoprism photoprism import
  
  # To search originals for faces without a complete rescan:
  # docker-compose exec photoprism photoprism faces index
  photoprism:
    image: photoprism/photoprism:240915
    container_name: photoprism
    depends_on:
      - photoprism_mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.photoprism.rule=Host(`photos.{{ local_domain }}`)"
      - traefik.http.services.photoprism.loadbalancer.server.port=2342
    environment:
      - "PHOTOPRISM_ADMIN_PASSWORD={{ init_admin_pass }}"          # YOUR INITIAL ADMIN PASSWORD (MINIMUM 8 CHARACTERS, USERNAME "admin")
      # PHOTOPRISM_AUTH_MODE: "public"               # authentication mode (public, password)
      - "PHOTOPRISM_SITE_URL=https://photos.{{ local_domain }}/"  # public server URL incl http:// or https:// and /path, :port is optional
      - "PHOTOPRISM_ORIGINALS_LIMIT=5000"               # file size limit for originals in MB (increase for high-res video)
      - "PHOTOPRISM_HTTP_COMPRESSION=gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      - "PHOTOPRISM_LOG_LEVEL=debug"                   # log level: trace, debug, info, warning, error, fatal, or panic
      - "PHOTOPRISM_READONLY=false"                   # do not modify originals directory (reduced functionality)
      - "PHOTOPRISM_EXPERIMENTAL=false"               # enables experimental features
      - "PHOTOPRISM_DISABLE_CHOWN=false"              # disables storage permission updates on startup
      - "PHOTOPRISM_DISABLE_WEBDAV=false"             # disables built-in WebDAV server
      - "PHOTOPRISM_DISABLE_SETTINGS=false"           # disables settings UI and API
      - "PHOTOPRISM_DISABLE_TENSORFLOW=false"         # disables all features depending on TensorFlow
      - "PHOTOPRISM_DISABLE_FACES=false"              # disables facial recognition
      - "PHOTOPRISM_DISABLE_CLASSIFICATION=false"     # disables image classification
      - "PHOTOPRISM_DISABLE_RAW=false"                # disables indexing and conversion of RAW files
      - "PHOTOPRISM_RAW_PRESETS=false"                # enables applying user presets when converting RAW files (reduces performance)
      - "PHOTOPRISM_JPEG_QUALITY=100"                    # image quality, a higher value reduces compression (25-100)
      - "PHOTOPRISM_DETECT_NSFW=false"                # flag photos as private that MAY be offensive (requires TensorFlow)
      - "PHOTOPRISM_UPLOAD_NSFW=true"                 # allows uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      - "PHOTOPRISM_DATABASE_DRIVER=mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      - "PHOTOPRISM_DATABASE_SERVER=photoprism_mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      - "PHOTOPRISM_DATABASE_NAME=photoprism"         # MariaDB or MySQL database schema name
      - "PHOTOPRISM_DATABASE_USER=photoprism"         # MariaDB or MySQL database user name
      - "PHOTOPRISM_DATABASE_PASSWORD={{ photoprism_db_password }}"       # MariaDB or MySQL database user password
      - "PHOTOPRISM_SITE_CAPTION=AI-Powered Photos App"
      - PHOTOPRISM_SITE_DESCRIPTION=""                # meta site description
      - PHOTOPRISM_SITE_AUTHOR=""                     # meta site author
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, clitools, clean):
      # PHOTOPRISM_INIT: "gpu tensorflow"
      ## Hardware Video Transcoding (for sponsors only due to high maintenance and support costs):
      - "PHOTOPRISM_FFMPEG_ENCODER=intel"        # FFmpeg encoder ("software", "intel", "nvidia", "apple", "raspberry")
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # FFmpeg encoding bitrate limit in Mbit/s (default: 50)
      ## Switch to a non-root user after initialization (supported IDs are 33, 50-99, 500-600, and 900-1200):
      - "PHOTOPRISM_UID={{ docker_compose_generator_uid }}"
      - "PHOTOPRISM_GID={{ docker_compose_generator_gid }}"
      - "PHOTOPRISM_AUTO_INDEX=60"
      - "PHOTOPRISM_AUTO_IMPORT=60"
      - "PHOTOPRISM_WORKERS=4"
  #     PHOTOPRISM_UMASK: 0000
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"
    devices:
      - "/dev/dri:/dev/dri"
    working_dir: "/photoprism"                # do not change or remove
    volumes:
  #     # "/host/folder:/photoprism/folder"                # Example
  #     - "{{ appdata_path }}/photoprism/originals:/photoprism/originals"               # Original media files (DO NOT REMOVE)
  #     # - "/example/family:/photoprism/originals/family" # *Additional* media folders can be mounted like this
  #     # - "~/Import:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "{{ photoprism_dir }}/storage:/photoprism/storage"
      - "{{ photoprism_dir }}/originals:/photoprism/originals"
      - "{{ photoprism_important }}:/photoprism/originals/Important:ro"
      - "{{ photoprism_dir }}/import:/photoprism/import"

  photoprism_mariadb:
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    image: mariadb:10.11
    container_name: photoprism_mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: 
      - "mysqld"
      - "--innodb-buffer-pool-size=512M"
      - "--transaction-isolation=READ-COMMITTED"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--max-connections=512"
      - "--innodb-rollback-on-timeout=OFF"
      - "--innodb-lock-wait-timeout=120"
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "{{ appdata_path }}/photoprism/database:/var/lib/mysql" # DO NOT REMOVE
    environment:
      - "MARIADB_AUTO_UPGRADE=1"
      - "MARIADB_INITDB_SKIP_TZINFO=1"
      - "MARIADB_DATABASE=photoprism"
      - "MARIADB_USER=photoprism"
      - "MARIADB_PASSWORD={{ photoprism_db_password }}"
      - "MARIADB_ROOT_PASSWORD={{ photoprism_db_password }}"
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ ntp_timezone }}"