---
- name: ensure target dir exists
  file:
    dest: "{{ frigate_config_filepath }}/"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"

- name: template frigate config
  template:
    src: templates/frigate.yml.j2
    dest: "{{ frigate_config_filepath }}/frigate.yml"
    force: yes
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  