---
- name: ensure target dir exists
  ansible.builtin.file:
    dest: "{{ frigate_config_filepath }}/"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"

- name: template frigate config
  ansible.builtin.template:
    src: templates/frigate.yml.j2
    dest: "{{ frigate_config_filepath }}/frigate.yml"
    force: yes
    # unsafe_writes: yes
    # backup: yes
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  