---

ansible_host: "{{ vault_kms_ip }}"

#########################################################
### Proxmox API connection and authentication section ###
#########################################################
pve_default_behavior: no_defaults
pve_node: pve1
pve_api_host: "{{ vault_pve1_host_ip }}"
pve_api_user: root@pam
pve_api_password: "{{ vault_proxmox_api_password }}"
# pve_api_token_id: root@pam!ansible
# pve_api_token_secret: "{{ vault_pve2_root_api_password }}"

#####################################
### Container OS template section ###
#####################################
pve_lxc_ostemplate_name: 'debian-12-standard_12.0-1_amd64.tar.zst'
pve_lxc_ostemplate_storage: iso_datastore
pve_lxc_ostemplate_content_type: vztmpl
pve_lxc_ostemplate_timeout: 60
pve_lxc_ostemplate_force: no
pve_lxc_ostemplate_state: present

##############################################
### Container resources definition section ###
##############################################
pve_lxc_timeout: 30
pve_hostname: "{{ inventory_hostname.split('.')[0] }}"
pve_lxc_vmid: 112
pve_lxc_description: |
  This host is a Debian 12 container configured via Ansible with:
  - 2 CPU cores
  - 2048 MB of RAM
  - 25 GB of system disk
  - unprivileged: no
  - onboot: yes
pve_lxc_root_password: "{{ vault_dockerlxc_root_password }}"
pve_lxc_root_authorized_pubkey: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

pve_lxc_cpu_cores: 2
pve_lxc_memory: 2048
pve_lxc_swap: 1024
pve_lxc_disk: 25
pve_lxc_storage: local_ssd
pve_onboot: yes
pve_lxc_searchdomain: "{{ vault_searchdomain }}"
pve_lxc_unprivileged: no
pve_lxc_force: no
pve_lxc_features:
  - nesting=1
  - mount=cifs;nfs
  - fuse=1
pve_lxc_net_interfaces:
  - id: net0
    name: eth0
    bridge: vmbr0
    hwaddr: FE:A8:38:9A:43:ED
    ip4: dhcp


#https://gist.github.com/scyto/e4e3de35ee23fdb4ae5d5a3b85c16ed3#file-vgpu-container-privileged-md


# List of additional mount points and their characteristics
# pve_lxc_mounts:
#   - id: mp1
#     storage: vms
#     size: 50
#     mount_point: "{{ appdata_path }}"
#     acl: false                     # Optional.
#     quota: false                   # Optional.
#     backup: false                  # Optional.
#     skip_replication: false        # Optional.
#     read_only: false               # Optional.
  # - id: mp1
  #   storage: local-lvm
  #   size: 8
  #   mount_point: "/mnt/logs"

# Additional "manual" settings to add to the file /etc/pve/nodes/{{ node }}/lxc/{{ VMID }}.conf
pve_lxc_additional_configurations:
#     # Kernel modules available within the LXC
  - regexp: '^mp0'
    line: "mp0: {{ appdata_path }},mp={{ appdata_path }}"
    state: present


local_domain: "kms.{{ domain_name }}"
zfs_path: /tank2
# ironicbadger.docker_compose_generator
appdata_path: "{{ zfs_path }}/appdata"
traefik_config_filepath: "{{ appdata_path }}/traefik-kms"


containers:
  ###
  - service_name: traefik
    active: true
    image: traefik
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`proxy.{{ local_domain }}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    volumes:
      - "{{ traefik_config_filepath }}:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    restart: unless-stopped
  ###
  - service_name: ejbca
    active: true
    image: keyfactor/ejbca-ce
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ejbca.entrypoints=websecure"
      - "traefik.http.routers.ejbca.rule=Host(`ejbca.{{ local_domain }}`)"
    volumes:
      - "{{ appdata_path }}/ejbca:/mnt/persistent/ejbcadb"
    environment:
      - "DATABASE_JDBC_URL=jdbc:h2:/mnt/persistent/ejbcadb;DB_CLOSE_DELAY=-1"
      - "TLS_SETUP_ENABLED=false"
    restart: unless-stopped
  ###
  